
export interface Coupon {
  id: string;
  title: string;
  description: string;
  image: string;
  expiresAt: string;
  category?: string;
  value: number;
  reason?: string; // Why this coupon was recommended
  isPersonalized?: boolean;
  aiGenerated?: boolean; // Whether the coupon was generated by AI
  conversionProbability?: number; // AI-predicted probability of user using this coupon
  brandId?: string; // Brand identifier for analytics
  campaignId?: string; // Campaign identifier for analytics
}

export interface CouponSwiperProps {
  onCouponSwiped?: (couponId: string, direction: string) => void;
  userId?: string;
}
